# base image
FROM node:12.9.1-alpine

# Override the base log level (info).
ENV NPM_CONFIG_LOGLEVEL warn

# Install and configure `serve`.
#RUN npm install -g serve
#CMD serve -s build


# Copy all local files into the image.
COPY . .

COPY package.json /data/
WORKDIR /data/
RUN npm install
ENV PATH /data/node_modules/.bin:$PATH

COPY . /data/app/
WORKDIR /data/app/

EXPOSE 3000

CMD [ "npm", "start" ]