# base image
FROM node:12.9.1-alpine

WORKDIR /usr/src/web

# Override the base log level (info).
ENV NPM_CONFIG_LOGLEVEL warn

# Install and configure `serve`.
#RUN npm install -g serve
#CMD serve -s build
EXPOSE 5000

# Copy all local files into the image.
COPY . .

# Install all dependencies of the current project.
# COPY package.json package.json

RUN npm install

CMD [ "npm", "start" ]