version: '3'

services:
  web:
    build:
      context: ./react-ui/coreui-free-react-admin-template-master
      dockerfile: Dockerfile_ui
    volumes:
      - ./react-ui/coreui-free-react-admin-template-master:/data/app
    ports:
        - "3000:3000"
    depends_on:
        - api

  api:
    build:
      context: ./API
      dockerfile: Dockerfile_Api
    volumes:
      - ./API:/usr/src/app
    ports:
        - "5001:5000"
    environment:
      PYTHONUNBUFFERED: 1
    
    restart: always
    depends_on:
        - db.pg


  db.pg:
    container_name: db.pg
    image: 'postgres:11.5-alpine'
    ports:
        - "5432:5432"
    environment:
      PG_PASSWORD: admin
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: docrec1
    volumes:
        - dbdata:/var/lib/postgresql/data
    restart: always
volumes:
  dbdata:

 
  